name: iptv-lan

on:
  push:
    branches: [main]
  schedule:
    - cron: "00 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install m3u8
          pip install bs4
          pip install lxml
          pip install html5lib
          pip install strict-rfc3339

      - name: Build
        run: |
          python3 ./script/iptv-lan.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update iptv-lan.m3u8"
          branch: main
          file_pattern: './playlist/iptv-lan.m3u8'
