name: iptv

on:
  push:
    branches: [main]
  schedule:
    - cron: "00 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull
        run: git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests m3u8 bs4 lxml html5lib strict-rfc3339

      - name: Build
        run: |
          python3 ./script/iptv.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update iptv.m3u8"
          branch: main
          file_pattern: |
            ./playlist/iptv-lan.m3u8
            ./playlist/iptv-wan.m3u8
