name: iptv

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install m3u8
          pip install bs4
          pip install lxml
          pip install html5lib
          pip install strict-rfc3339

      - name: Build home
        run: |
          python3 ./script/iptv.py


      - name: Commit
        run: |
          git config --global user.name '0x648'
          git config --global user.email '0x648@github.com'
          git add .
          git commit -am "Automated build"
          git push



